// <auto-generated />
using System;
using BATTLESHIP_CORE_EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BATTLESHIP_CORE_EF.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20210213140846_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("BATTLESHIP_CORE_EF.Models.ActionMove", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoardGAMES_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GAME_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PLAYER")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RESULT")
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("BoardGAMES_ID");

                    b.ToTable("ActionMove");
                });

            modelBuilder.Entity("BATTLESHIP_CORE_EF.Models.ActionShipInstall", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoardGAMES_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GAME_ID")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IS_HIT")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PLAYER")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SHIP_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SHIP_ID1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("BoardGAMES_ID");

                    b.HasIndex("SHIP_ID1");

                    b.ToTable("ActionShipInstall");
                });

            modelBuilder.Entity("BATTLESHIP_CORE_EF.Models.Board", b =>
                {
                    b.Property<int>("GAMES_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RESULT_WIN")
                        .HasColumnType("TEXT");

                    b.Property<int>("SIZE_X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SIZE_Y")
                        .HasColumnType("INTEGER");

                    b.Property<string>("STATUS")
                        .HasColumnType("TEXT");

                    b.HasKey("GAMES_ID");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("BATTLESHIP_CORE_EF.Models.Ship", b =>
                {
                    b.Property<int>("SHIP_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SHIP_NAME")
                        .HasColumnType("TEXT");

                    b.Property<int>("SIZE_X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SIZE_Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("SHIP_ID");

                    b.ToTable("Ship");
                });

            modelBuilder.Entity("BATTLESHIP_CORE_EF.Models.ActionMove", b =>
                {
                    b.HasOne("BATTLESHIP_CORE_EF.Models.Board", "Board")
                        .WithMany("ActionMove")
                        .HasForeignKey("BoardGAMES_ID");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("BATTLESHIP_CORE_EF.Models.ActionShipInstall", b =>
                {
                    b.HasOne("BATTLESHIP_CORE_EF.Models.Board", "Board")
                        .WithMany("ActionShipInstall")
                        .HasForeignKey("BoardGAMES_ID");

                    b.HasOne("BATTLESHIP_CORE_EF.Models.Ship", "Ship")
                        .WithMany("ActionShipInstall")
                        .HasForeignKey("SHIP_ID1");

                    b.Navigation("Board");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("BATTLESHIP_CORE_EF.Models.Board", b =>
                {
                    b.Navigation("ActionMove");

                    b.Navigation("ActionShipInstall");
                });

            modelBuilder.Entity("BATTLESHIP_CORE_EF.Models.Ship", b =>
                {
                    b.Navigation("ActionShipInstall");
                });
#pragma warning restore 612, 618
        }
    }
}
